config/routes.rb
Rails.application.routes.draw do
  
    root 'static_pages#home'
    resources :users
    resources :microposts
    
    get     'sessions/new'
    get     '/signup',  to: 'users#new'
    post    '/signup',  to: 'users#create'
    
    resources :microposts do
        member do
            get 'add'
        end
    end
    
    resources :users do
        member do
            get 'bookshow'
        end
        member do
            get 'bookreview'
        end
    end
    
    get     '/login',   to: 'sessions#new'
    post    '/login',   to: 'sessions#create'
    get     '/contact', to: 'static_pages#contact'
    delete  '/logout',  to: 'sessions#destroy'
    
    delete  '/users/:id/bookshow',  to: 'microposts#destroy'
    
    get '/ranking', to: 'book#show'
    
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true
  validates :title, presence: true
  validates :imagecont, presence: true
  validates :auth, presence: true
  validates :release, presence: true
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only:[:new, :create, :destroy]
  before_action :correct_user, only: :destroy
   
  def index
    @microposts = Micropost.rank(:row_order)
  end
  
  def new
    @micropost = Micropost.new
    
    if params[:keyword].present?
      #　デバックログ出力するために記述
      Amazon::Ecs.debug = true

      # Amazon::Ecs::Responceオブジェクトの取得
      books = Amazon::Ecs.item_search(
        params[:keyword],
        search_index:  'Books',
        dataType: 'script',
        response_group: 'ItemAttributes, Images',
        country:  'jp',
        power: "Not kindle"
      )

      # 本のタイトル,画像URL, 詳細ページURL, 著者, 発売日の取得
      @books = []
      books.items.each do |item|
        book = Book.new(
          item.get('ItemAttributes/Title'),
          item.get('LargeImage/URL'),
          item.get('DetailPageURL'),
          item.get('ItemAttributes/Author'),
          item.get('ItemAttributes/PublicationDate')
        )
        @books << book
      end
    end
  end
  
  def create
    @micropost = current_user.microposts.build(micropost_params)
    
		if @micropost.save
			redirect_to current_user
		else
			render 'new'
		end
		
  end

  def destroy
  	@micropost.destroy
  	redirect_to current_user
  end
  
  def show
  end
  
  def add
  end
  

  private

    def micropost_params
      params.require(:micropost).permit(:content, :title, :imagecont, :auth, :release)
    end
    
    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
  
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_book_list.html.erb
<% if @books.present? %>
  <% @books.each do |book| %>
      <%= form_for(@micropost) do |f| %>
        <%= link_to (image_tag(book.image_url, style: "width: 70px;height: 100px;display: inline-block;")), book.url, :target=>["_blank"] %>
        <div id="kensakutitle"><%= book.title %></div>
        <%= f.hidden_field :content,   value: book.url %>
        <%= f.hidden_field :title,     value: book.title %>
        <%= f.hidden_field :imagecont, value: book.image_url %>
        <%= f.hidden_field :auth,      value: book.author %>
        <%= f.hidden_field :release,   value: book.release %>
        <%= f.submit "本棚に追加" , id:"addhondana" %>
        
      <% end %>
  <% end %>
<% end %>

app/views/microposts/_micropost.html.erb
<figure>
  <%= link_to(image_tag(micropost.imagecont, style: "width: 70px;height: 100px;display: inline-block;"), bookshow_user_path(:id => current_user, :booktitle => micropost.title,
              :bookimg => micropost.imagecont, :bookurl => micropost.content, :bookauthor => micropost.auth, 
              :bookrelease => micropost.release), 
              remote: true) %>
  <figcaption><div class="bookname"><%= micropost.title.gsub(/\(.+?\)/, "").truncate(14) %></div></figcaption>
  <div class='deletemark'><%= link_to(image_tag('/images/batsu.png', style: "width: 13px;height: 13px; display: inline-block;"), micropost, method: :delete) %></div>
</figure>

app/views/microposts/new.html.erb
<div id="container">
<div class='itemposition'>
  <div id="search-box">
    <%= form_tag(new_micropost_path, method: :get) do %>
        <%= text_field_tag :book, "",  id: "book_add_form", name: "keyword", autocomplete:"off", placeholder: "キーワードを入力してください", style: "width: 300px; height:40px;" %>
        <button title="検索" type="submit" class="kensaku">検索</button>

    <% end %>
  </div>
  
  <div id='book_list'>
   <%= render partial: 'book_list' %>
  </div>
  
</div>
</div>