config/routes.rb
Rails.application.routes.draw do
  
    root 'static_pages#home'
    resources :users
    resources :microposts
    
    get     'sessions/new'
    get     '/signup',  to: 'users#new'
    post    '/signup',  to: 'users#create'
    
    resources :microposts do
        member do
            get 'add'
        end
    end
    
    resources :users do
        member do
            get 'bookshow'
        end
        member do
            get 'bookreview'
        end
    end
    
    get     '/login',   to: 'sessions#new'
    post    '/login',   to: 'sessions#create'
    get     '/contact', to: 'static_pages#contact'
    delete  '/logout',  to: 'sessions#destroy'
    
    delete  '/users/:id/bookshow',  to: 'microposts#destroy'
    
    get '/ranking', to: 'book#show'
    
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <ul class="footer__item">
      <%= link_to "お問い合わせ", "/contact" %>
      <small>
        &copy; 2018 HONS.
      </small>
    </ul>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
          
          <a class="navbar-brand" href="/">HONS</a>
        </div>

            <ul class="nav navbar-nav navbar-right">
                  <% if logged_in? %>
                    <li class="navlist-hondana"><%= link_to "本棚", current_user %></li>
                    <li class="navlist-add"><%= link_to "本を追加", new_micropost_path %></li>
                    <li class="navlist-setting"><%= link_to "アカウント設定", edit_user_path(current_user) %></li>
                    <li class="navlist-logout"><%= link_to "ログアウト", logout_path, method: :delete %></li>
                  <% else %>
                    <li class="navlist-login"><%= link_to "ログイン", login_path %></li>
                  <% end %>
            </ul>
            
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag('/images/favicon.ico') %>

    <title><%= yield(:title) %>HONS</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>

  </head>
  <body>
    <%= render 'layouts/header' %>
  
    
    <%= yield %>
  </body>
  
</html>